### ISSUE TITLE
Tag Pileup off by 1 error

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/scriptmanager#11] opened 2018-02-23 19:37 UTC
The output composite plot x-axis for tag pileup is sometimes off by 1 bp depending on whether the input bed file is even or odd.

**Comment by owlang** [comment] 2021-12-24 12:54
This issue cannot be replicated after fixing #75. Either the composite plot x-axis tick labels were causing some confusion or it had a shared root cause with #75 and has been incidentally fixed. Closing...

**Closed by owlang** 2021-12-24 12:54 UTC
Labels: bug
